version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    build:
      html:
        - echo "Copying static X3D files..."
	    - mkdir -p $READTHEDOCS_OUTPUT/html/_static/x3d
	    - cp -r ./source/_static/x3d $READTHEDOCS_OUTPUT/html/_static/x3d
        - python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
formats:
    - htmlzip
conda:
    environment: doc/environment.yml
python:
    install:
        - method: pip
          path: .
sphinx:
    configuration: doc/source/conf.py
