version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
formats:
    - htmlzip
conda:
    environment: doc/environment.yml
python:
    install:
        - method: pip
          path: .
sphinx:
    configuration: doc/source/conf.py
