name: Build Project

on:
  pull_request:

  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build_wheels_and_sdist:
    name: Build wheels and sdist
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@204dc7c0f82720090703712694b7cab761aacaa0 # 0.13.0
    - name: Build wheels and sdist
      run: uv build --sdist --wheel --out-dir dist/ .
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: wheel
        path: dist/*.whl
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: sdist
        path: dist/*.tar.gz

  Publish:
    name: Publish to PyPI
    needs: [build_wheels_and_sdist]
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download artifact sdist
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: sdist
        path: dist
    - name: Download artifact wheel
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: wheel
        path: dist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
